name: README.md update

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  schedule:
    - cron: "00 03 * * *" #GMT+08 11:00
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
  
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install Pillow
        pip install requests
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Gettings files from Repo
      uses: actions/checkout@v4

    - name: Update README.md
      run: |
        python3 BinWP.py -u

    - name: Commit and push changes to branch master
      uses: actions-js/push@master
      with:
        force: true
        branch: "master"
        user_name: ${{ secrets.USER_NAME }}
        user_email: ${{ secrets.USER_EMAIL }}
        github_token: ${{ secrets.TOKEN_REPO }}
        commit_message: "daily update README.md"
