name: README.md update

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  schedule:
    - cron: "00 03 * * *" #GMT+08 11:00
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
  
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install Pillow
        pip install requests
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Gettings files from Repo
      uses: actions/checkout@v4
      with:
        persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal access token.
        fetch-depth: 0 # otherwise, there would be errors pushing refs to the destination repository.

    - name: Update README.md
      run: |
        python3 BinWP.py -u

    - name: Commit files
      run: |
        git config --local user.email ${{ secrets.USER_EMAIL }}
        git config --local user.name ${{ secrets.USER_NAME }}
        git commit -a -m "daily update README.md"

    - name: Push changes to branch master
      uses: ad-m/github-push-action@master
      with:
        force: true
        branch: "master"
        github_token: ${{ secrets.TOKEN_REPO }}
